def test ():
  print("my work is done.")
  print("Baddest boy.")
  print("cyrille.")
  print("HELLO WORLD.")
  print("manchester united.")
  print("On God.")
  print("fine me.")
  print("hello world in cocming.")
  print("cyber sercurity.")
  print("hello world.")
  print("age.")
  input("what is your name?")
  print(5 + 5)